#
# SPDX-FileCopyrightText: Katastima Authors
# SPDX-License-Identifier: EUPL-1.2
#

# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# see: https://kotlinlang.org/docs/releases.html
kotlin = "2.4.10"
# see: https://github.com/Kotlin/kotlinx-datetime/releases
kotlinxDatetime = "0.8.0"
# see: https://github.com/Kotlin/kotlinx.serialization/releases
kotlinxSerializationJSON = "1.11.0"
# see: https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinxCoroutines = "1.11.0"

# see: https://mvnrepository.com/artifact/com.android.tools.build/apksig
apksig-version = "9.3.1"

# see: https://github.com/iBotPeaches/Apktool/releases
apktool = "3.0.3"

# see: https://github.com/ajalt/clikt/releases
clikt = "5.1.0"

# see: https://github.com/JetBrains/Exposed/releases
exposed = "1.4.0"

# see: https://github.com/h2database/h2database/releases
h2 = "2.4.240"

# see: https://jreleaser.org/guide/latest/release-history.html
jreleaser = "1.25.0"

# see: https://github.com/charleskorn/kaml/releases
kaml = "0.104.0"

# see: https://github.com/qos-ch/logback/releases
logback = "1.6.1"

# see: https://square.github.io/okio/changelog/
okio = "3.18.1"

# see: https://github.com/qos-ch/slf4j/releases
slf4j = "2.0.18"

# see: https://github.com/GradleUp/shadow/releases
shadow-gradle = "9.6.1"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

apksig = { module = "com.android.tools.build:apksig", version.ref = "apksig-version" }
apktool-lib = { module = "org.apktool:apktool-lib", version.ref = "apktool" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-jul = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }

# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
exposed = ["exposed-core", "exposed-dao", "exposed-jdbc", "h2"]
logging = ["logback-classic", "logback-core", "slf4j-api", "slf4j-jul"]

[plugins]
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadowGradlePlugin = { id = "com.gradleup.shadow", version.ref = "shadow-gradle" }
